// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDai1W1Cbi1ob3HUUPNIhlZJdQPJcnhk3Q',
    appId: '1:947788597791:web:5f2e61c46c359536e7632a',
    messagingSenderId: '947788597791',
    projectId: 'drawing-calculator',
    authDomain: 'drawing-calculator.firebaseapp.com',
    storageBucket: 'drawing-calculator.appspot.com',
    measurementId: 'G-LCD3C6P8FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFU3U6GrPJ2l4QEa3ALi8z51jGrYtefg',
    appId: '1:947788597791:android:267e9510e8f0e38de7632a',
    messagingSenderId: '947788597791',
    projectId: 'drawing-calculator',
    storageBucket: 'drawing-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aW9xUQwKO7YXaiO-QAefTXE-ZsIQyU8',
    appId: '1:947788597791:ios:e9d6ac49b9dff4dce7632a',
    messagingSenderId: '947788597791',
    projectId: 'drawing-calculator',
    storageBucket: 'drawing-calculator.appspot.com',
    iosBundleId: 'com.example.drawingCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aW9xUQwKO7YXaiO-QAefTXE-ZsIQyU8',
    appId: '1:947788597791:ios:e9d6ac49b9dff4dce7632a',
    messagingSenderId: '947788597791',
    projectId: 'drawing-calculator',
    storageBucket: 'drawing-calculator.appspot.com',
    iosBundleId: 'com.example.drawingCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDai1W1Cbi1ob3HUUPNIhlZJdQPJcnhk3Q',
    appId: '1:947788597791:web:e5c269935f73b219e7632a',
    messagingSenderId: '947788597791',
    projectId: 'drawing-calculator',
    authDomain: 'drawing-calculator.firebaseapp.com',
    storageBucket: 'drawing-calculator.appspot.com',
    measurementId: 'G-M6BLTW8SW7',
  );

}